eval:
  iterations: 10
  merge_gap_frac: 0.15
  negative_set_batch_size: 8
  min_duration_frac: 0.25
  query_batch_size: 4
  samples_neg: 50
  threshold: 0.45
features:
  eps: 2.220446049250313e-16
  fmax: 11025
  fmin: 50
  hop_mel: 256
  hop_seg: 0.1
  n_fft: 512
  n_mels: 128
  n_mfcc: 0
  seg_len: 0.2
  sr: 22050
  train_limit: 0
  use_delta_mfcc: false
model:
  resnet:
    pool_time_only: true
  transformer:
    conv_channels:
    - 32
    - 64
    conv_stem: true
    d_model: 128
    dim_feedforward: 256
    dropout: 0.1
    nhead: 4
    num_layers: 2
path:
  Model: ${path.root_dir}/Model
  best_model: ${path.Model}/best_model.pth
  eval_dir: /media/vic/ext_disk/UAM_master/DL4AP/final_project/Few-shot-Bioacoustic-Event-Detection/data/raw/development/Development_Set/Validation_Set
  feat_eval: ${path.feat_path}/feat_eval
  feat_path: ${path.root_dir}/Features
  feat_train: ${path.feat_path}/feat_train
  last_model: ${path.Model}/last_model.pth
  root_dir: /media/vic/ext_disk/UAM_master/DL4AP/final_project/Few-shot-Bioacoustic-Event-Detection
  train_dir: /media/vic/ext_disk/UAM_master/DL4AP/final_project/Few-shot-Bioacoustic-Event-Detection/data/raw/development/Development_Set/Training_Set
set:
  eval: true
  features: false
  train: true
train:
  device: cuda
  encoder: Resnet
  epochs: 1
  k_way: 5
  lr_rate: 0.001
  n_shot: 5
  num_classes: 15
  num_episodes: 2000
  scheduler_gamma: 0.5
  scheduler_step_size: 10
